modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'GPL-3.0-only'
showAsResourcePack = false
mods = [
	{
		modId = 'zen_level_up',
		version = '2.0.4', 
		displayName = 'Level-Up', 
		description = "Level Up\nis a Skill Datapack. Level your Skills by playing.", 
		logoFile = 'pack.png', 
		authors = 'Zensiert', 
		displayURL = 'https://modrinth.com/datapack/level-up'
	}
]